version: "3.9"
services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example

  pgadmin:
    build: .
    restart: always
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: example
      POSTGRES_PASSWORD: example
    ports:
      - 8081:80
